parameters:
    routes_basepath: /routes

cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
            route_basepath: '%routes_basepath%'

    auto_mapping: false
    mapping:
        resources:
            - '%kernel.project_dir%/config/automatic_routes.yml'
