cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default:             100
    dynamic:
        persistence:
            phpcr:
                enabled: true
                route_basepaths:
                    - '%routes_basepath%'
        route_collection_limit: 50
