doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            caches:
                meta: doctrine_cache.providers.phpcr_meta
                nodes: doctrine_cache.providers.phpcr_nodes
            logging:   true
            profiling: true
        workspace: default
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"
