App\Document\Page:
    definitions:
        view:
            uri_schema: /{title}
            defaults:
                _controller: 'App\Controller\PagesController::view'
    token_providers:
        title: [content_method, {method: getTitle}]
